Vagrant.configure("2") do |config|
    config.vm.box = "fedora/30-cloud-base"
    config.vm.box_version = "30.20190425.0"

  config.vm.define "host1" do |host1|
    host1.vm.network "private_network", ip: "192.168.100.1"
  end

  config.vm.define "host2" do |host2|
    host2.vm.network "private_network", ip: "192.168.100.2"
  end
end
